name: elderly_care_companion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  table_calendar: ^3.1.2
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^4.2.1
  http: ^1.2.2
  speech_to_text: ^6.6.2
  flutter_tts: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
